<a href="https://colab.research.google.com/github/Juilin77/ML/blob/main/introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 64. NumPy DataTypes and Attributes
import numpy as np

## DataTypes & Attributes

In [2]:
# NumPy's main datatype is ndarray (array, 陣列)
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
a1.shape

(3,)

In [4]:
#type(a1)

In [5]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]],
              [[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18]]])

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
# show dimension (維度)
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
#type(a1), type(a2), type(a3)

In [15]:
# Create a DataFrame from a NumPy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# 65. Creating NumPy Arrays

In [16]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int64')

In [18]:
# np.ones ([2, 3]) 建立一個用one (1) 填滿的2列3欄
ones = np.ones([2, 3])

In [19]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [21]:
# np.zeros ([2, 3]) 建立一個用zero (0) 填滿的2列3欄
zeros = np.zeros((2, 3))

In [22]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
# 建立一個一維的陣列 (數值最小為0, 最大為10, 間隔為2)
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [24]:
# 建立一個2維(3 * 5)的陣列 (數值最小為0, 最大為10, 3*5的二維陣列)
random_array = np.random.randint(0, 10, size = (3, 5))
random_array

array([[5, 1, 9, 1, 2],
       [6, 7, 5, 6, 8],
       [5, 3, 6, 4, 6]])

In [25]:
random_array.size

15

In [26]:
random_array.shape

(3, 5)

In [27]:
# 建立一個2維(5 * 3)的陣列, 數值會在0-1之間
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.9423071 , 0.58687702, 0.50583644],
       [0.00667914, 0.34773392, 0.21075575],
       [0.14101871, 0.97168733, 0.1622164 ],
       [0.84036626, 0.67614886, 0.35948578],
       [0.71720921, 0.8351055 , 0.7412073 ]])

In [28]:
random_array_2.shape

(5, 3)

In [29]:
# 建立一個2維(5 * 3)的陣列, 數值會在0-1之間
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.95881572, 0.0084436 , 0.77331349],
       [0.22012813, 0.50698928, 0.2089098 ],
       [0.52739351, 0.33800107, 0.45120857],
       [0.14023447, 0.40830958, 0.21059075],
       [0.5978046 , 0.38025738, 0.78618242]])

## 66. NumPy Random Seed

In [30]:
# Pseudo-random (偽隨機性) numbers
# .seed(seed=0), 這會建立一個隨機值(種子值可為其他數值 "seed=0"), 但該值不會每次都變. 如果沒有這行, 隨機值每次都會變
np.random.seed(seed=99999)
# randint (整數), 最小值是0, 最大值是9 size = 建立一個5列3欄的矩陣
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [31]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [32]:
random_array_4.shape

(5, 3)

## 67. Viewing Arrays and Matrices

In [33]:
# how to find unique elements in numpy array
# numpy.unique https://numpy.org/doc/stable/reference/generated/numpy.unique.html
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [34]:
a1

array([1, 2, 3])

In [35]:
a1.shape

(3,)

In [36]:
a1[0]

1

In [37]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [38]:
a2.shape

(2, 3)

In [39]:
a2[0]

array([1. , 2. , 3.3])

In [40]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [41]:
a3.shape

(2, 3, 3)

In [42]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
# 取Axis 0的頭兩個數值(:2), 取Axis 1的頭兩個數值(:2), 取Axis 2的頭兩個數值(:2)
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [54]:
#
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[0, 5, 3, 0, 5],
         [7, 1, 8, 4, 9],
         [0, 2, 0, 7, 6],
         [2, 9, 9, 5, 1]],

        [[0, 0, 9, 1, 1],
         [5, 3, 2, 0, 4],
         [8, 7, 1, 4, 9],
         [3, 6, 7, 1, 0]],

        [[2, 7, 0, 0, 9],
         [8, 2, 0, 5, 5],
         [0, 9, 0, 8, 4],
         [5, 1, 4, 0, 7]]],


       [[[2, 0, 3, 9, 8],
         [3, 7, 1, 0, 1],
         [4, 6, 1, 0, 1],
         [0, 1, 8, 4, 1]],

        [[6, 8, 5, 2, 4],
         [7, 4, 1, 2, 8],
         [5, 2, 9, 6, 2],
         [5, 7, 7, 5, 5]],

        [[6, 0, 6, 4, 6],
         [2, 6, 8, 7, 0],
         [5, 8, 9, 7, 7],
         [6, 2, 5, 6, 1]]]])